### ISSUE TITLE
Make menu appear next to cursor

### ISSUE THREAD

**Issue by madprops** [nkappler/ctxmenu#36]
Sometimes the trigger button that is clicked to show the context menu is very long, in my case. 

So if I click near the middle of it, the menu still appears on the top. 

Wondering if there's a way to make the context menu appear near the location of the trigger click?

**Comment by nkappler** [comment]
Passing an event instead of an element to the `show` function should do the trick.
You can observe the difference on the demo page (https://nkappler.de/ctxmenu/)
The Button "Click this Button" passes an event and the menu sticks to the cursor, the 'button' below (which is a span element passes an element instead and the menu is attached to the elements coordinates.
Also see: 
https://github.com/nkappler/ctxmenu#ctxmenushow

Code example

```html
<!-- Use This:                                                   v  -->
<button type="button" onclick="e => ctxmenu.show([ /* menu */ ], e)">Click this Button!</button>
<!-- Not This:                                                     vvvvvv  -->
<button type="button" onclick="e => ctxmenu.show([ /* menu */ ], e.target)">Click this Button!</button>
```

![3F48B084-21B9-4C00-9ECD-91816394AAC4](https://user-images.githubusercontent.com/9429273/156769296-dff8d1be-c5ea-4624-96e7-b2b7e2b355f1.GIF)
