### ISSUE TITLE
Submenus containing multiple items may sometimes be displayed outside of the viewport

### ISSUE THREAD

**Issue by Mahenintsoa** [nkappler/ctxmenu#50]
### Observed Behaviour
When a submenu with several items is opened from a menu that already appears at the bottom of the viewport, the submenu is displayed incorrectly the first time.

![image](https://github.com/nkappler/ctxmenu/assets/44357293/b47fc2e0-f519-4224-8324-9d3b05d631d5)

### Reproducer
I've made a simple html file to reproduce the issue if needed
[example-ctxmenu.zip](https://github.com/nkappler/ctxmenu/files/14423366/example-ctxmenu.zip)

### Possible fixes
It appears that when the direction is set to "u", the code no longer takes the height of the submenu into account when calculating the vertical position.

**Comment by nkappler** [comment]
That's an excellent catch, thank you.
Honestly, ever since it was discovered that the positioning code breaks down, when zoom is applied to the page, the code to determine the correct position has grown into a bit of a mess.
I'm currently in the middle of a bigger refactoring, so I totally expect this code to change in the near future.

In the meantime, I'll merge your fix and release a patch. Thanks for your contribution.
