### ISSUE TITLE
Add possibility to add classes to item

### ISSUE THREAD

**Issue by JohnJVTK** [nkappler/ctxmenu#52]
Hello !

I was looking for a plugin generating context menus but without jQuery and I found yours.
It's really nice and it does almost everything I need.

Could you add a standard property "classes" that would be added to item ? To the generated <span> ideally.
Something like that :
```
items.push({
    text: "Test",
    classes : "class1 class2 class3", // OR ["class1","class2","class3"]
    action: () => console.log('test')
});
```
It would render something like that :
```
<ul class="ctxmenu" style="...">
    <li class="interactive">
        <span class="class1 class2 class3">Test</span>
    </li>
</ul>
```
I know I can do it with the property "html" but it would be easier with a "classes" property.

Thanks by advance,
John

**Comment by nkappler** [comment]
Hi John, thanks for your feedback.

I currently have a fix for #49 in the pipeline, which is almost ready.
Whils't this change does not include this functionality, it makes preperations for it, so it can be done more easily in the future. If you're interested you can follow the discussion there.

Currently I'm in the finishing process for this update, but based on your feedback, I might include your suggestion too and fix both at once.

**Comment by nkappler** [comment]
Hi @JohnJVTK 

I've implemented your feature request on the [onHide](https://github.com/nkappler/ctxmenu/tree/onHide) branch.
If you wish you can download the frehsly compiled version of ctxmenu from there.

I need to write some documentation for it and I want to deprecate the `style` attribute, since it is duplicate functionality now and I will be able to remove some code in the future, but I'll do that in a future update, I am currently working on over on the refactoring branch.

Once the documentation and type declarations are ready, I'll publish version 1.7, containing this feature and #49

**Comment by nkappler** [comment]
Hi @JohnJVTK 

I've just released version `1.7.0` which includes this feature request.
Please let me know if you have any questions or feedback.

If you find this repository valueable, please consider giving it a star ⭐, it helps with visibility.

Happy Coding 😄

**Comment by JohnJVTK** [comment]
Thanks for being so reactive.
I just tried it and it works fine for class attribute, didn't test with others like id or name.

Maybe you should provide a clear exemple in your home page in "Menu Definition" or elsewhere because I had to look in your code review and in your tests to find out how to implement it.

5-stars project 🥇

**Comment by nkappler** [comment]
Hi @JohnJVTK 
I've documented the feature in the [readme](/README.md#ctxconfig) but yes, adding an example is a very good idea.
I'll do that tomorrow...
