### ISSUE TITLE
prevent override on control key down

### ISSUE THREAD

**Issue by 314parley** [nkappler/ctxmenu#54]
hi! just stumbled upon your project and was wondering if there was a way to override the ctxmenu from showing, and doing the default browser context menu when control is held down. this seems to be working properly on Firefox, but on Chromium-based browsers, it doesn't work properly.

**Comment by nkappler** [comment]
Hi @314parley,

By using `show` instead of `attach` and wrapping it in your own context menu event handler, this is easily achievable:

[codepen demo](https://codepen.io/nkappler/pen/dyLNbop)
```javascript
document.body.addEventListener("contextmenu", e => {
  if(e.getModifierState("Control")) { return; }
  
  ctxmenu.show([{text: "Hello World"}], e);
});
```

<hr />

> this seems to be working properly on Firefox

What do you mean exactly? Does the context menu not show up on Firefox when the control key is pressed? I'd consider that a bug.

**Comment by nkappler** [comment]
> What do you mean exactly? Does the context menu not show up on Firefox when the control key is pressed? I'd consider that a bug.

I've just tried both the default behaviour and my example above in Firefox and both work as expected.

Could you further elaborate what you did and why it didn't meet your expectations?

**Comment by 314parley** [comment]
oh, that worked! I had no idea about ctxmenu.show, whoops! I thought I *had* to attach it to html. thanks!
