### ISSUE TITLE
Good job. Recomendations.

### ISSUE THREAD

**Issue by musicman3** [nkappler/ctxmenu#9]
Very good work. But the documentation is weak. More examples are needed. You also need beautiful skins. It's not a problem for me, but people will need it. I figured it out, but not right away. I hope the project will develop. We are preparing to integrate this menu into our project.

**Comment by nkappler** [comment]
Hi Alex,
Thank you very much, I am glad you like it.
Which parts of the documentation are unclear to you? I think the documentation covers about everything, however it is hard to judge how somebody foreign to the project will interpret / understad it.
Please let me know if you have questions, I am happy to help.

Providing skins is a good idea, feel free to open a pull request if you want. I might not be able to spend time on this in the near future.

**Comment by nkappler** [comment]
You can already write your own skins, there are just no premade ones yet.

**Comment by musicman3** [comment]
I am not clear on how the callback for ctxmenu.update works. I need to insert a <select> </select> after initializing a menu to a menu section. I see an option that you can try to do this through a callback. I can't do it. Everything else worked out well. How can you do this? Any ideas?

**Comment by nkappler** [comment]
There's an example about the callback function in the demo code (https://github.com/nkappler/ctxmenu/blob/master/docs/demo.js)

```javascript
ctxmenu.attach("html", [
    {
        text: "Actions",
        tooltip: "JS Functions"
    },
    //  ... lots more menu items
    { isDivider: true },
    { text: "Event specific stuff" }
], function (m, e) {
    m.push({
        text: "e.g. Cursor Position: X:" + e.clientX + " / Y:" + e.clientY,
        href: "",
        disabled: true
    });
    return m;
}); 
```

The callback functions will get two parameters passed: the menu definition `m` and the event `e`.
In the example above I add a menu item which displays the view coordinates of the cursor, when the menu gets triggered)
In the callback you can further change the menu definition before it is shown.
Be aware that you need to return the new or altered menu definition, otherwise the callback will have no effect.

Also, ```<select />``` elements are not supported yet, would a submenu work for you?
Otherwise we could try to make a generic menu item where you pass your own DOM node 🤔
Shouldn't be too much work, note though that a `<select />` element cannot be styled much with css since it is rendered by the operating system.

> P.S. How do you know the name Sasha? Do you speak Russian? ))

No, unfortunately not, but I know somebody with russian roots named Alexander, thus I know about this :)

**Comment by musicman3** [comment]
I think that can create a `<select>` list in advance as a string, and then add it

**Comment by nkappler** [comment]
I am not quite sure what you are trying to achieve.
Is the `<select>` element independent of the context menu or should it be part of it?

If it is independent you might want to use the action Item, which executes a give function upon pressing it in the context menu:

```javascript
{
    text: "This is an action item",
    action: () => alert("This is shown when the item is pressed"),
}
```

The callback functions of `attach` or `update` are called *before* the menu is opened, i.e. on rightclick.

**Comment by musicman3** [comment]
The <select> element is inserted into the menu. The <select> list can be prepared in advance, or prepared at initialization. 

<select> must be displayed in the desired section.

**Comment by musicman3** [comment]
I did it with a prepared list. I think this is a good solution.  Thanks

**Comment by nkappler** [comment]
Try
```javascript
disabled: stiker === 0
```
or
```javascript
disabled: !stiker
```
is always a number.

If you need the condition to be evaluated at exactly the moment when the menu is opened,
Use the `update` method with a callBack function.

**Comment by nkappler** [comment]
Allowing callback functions for each property is a good idea though.
I might add that, thanks 👍

**Comment by musicman3** [comment]
My check is done using the following function: 

```
disabled: function () {
                        let params = (new URL(document.location)).searchParams;
                        if (params.get('search') !== null || Number(parent_id) === 0) {
                            return true;
                        }
                    },
```

So I don’t know how to check without a function

**Comment by nkappler** [comment]
looks great aready 👍

The main objective when I developed this was that it had to be simple, no dependencies and I needed a few functionalities for another project, like submenus and event specific stuff.
I have thought about adding icon support and more, but it was sufficient for me at the time so I postponed it.

Thanks a lot for your feedback, it is highly valuable for me since it shows a few weak spots.
I'll work on some updates on the weekend, I've created some issues for the planned features (https://github.com/nkappler/ctxmenu/issues)

Do you mind sharing your whole menu implementation with me?

**Comment by musicman3** [comment]
swisnl/jQuery-contextMenu was 89 kb and your code is 11 kb. Your settings allow you to do even a little more. I like this simple and functional solution.

**Comment by nkappler** [comment]
You are not using typescript, are you?
The inline documentation is also pretty verbose and hopefully helpful:
![grafik](https://user-images.githubusercontent.com/9429273/106798836-d1ef1e00-665e-11eb-87d9-b54025b2fd40.png)

**Comment by nkappler** [comment]
Hi Sasha,

Thanks again for your feedback! 🥇
I am about ready to release 1.2 and will do so soon.

I still need to update the documentation, not sure If I will also add it today.

If you find any bugs, please let me know.

I will close this issue now, if there is anything else you need help with, let me know 😃

**Comment by musicman3** [comment]
All functions are working fine now. Very good menu. A lot of possibilities. Very good work!
